[project]
name = "dhcw-software-engineering-handbook"
version = "0.1.0"
description = "DHCW Software Engineering Handbook"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "zensical>=0.0.7",
]

[tool.uv]
required-version = ">=0.10.0"
